name: Deploy driver to Oracle Free Tier

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy driver-services to Oracle Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.ORACLE_HOST_IP }}
          username: ${{ secrets.ORACLE_USERNAME }}
          key: ${{ secrets.ORACLE_SSH_KEY }}
          script: |
            cd ~/proyecto-web/driver
            git pull origin master
            
            cd ~/proyecto-web
            docker-compose up -d --build driver-services
